/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Carro;
import model.Pessoa;
import servicos.CarroServicos;
import servicos.PessoaServicos;
import servicos.ServicosFactory;
import util.Validadores;

/**
 *
 * @author 182120069
 */
public class JFCarro extends javax.swing.JFrame {

    /**
     * Creates new form JFCarro
     */
    public JFCarro() {
        initComponents();
        this.setLocationRelativeTo(null);
        jbDeletar.setVisible(false);
        addRowToTable();
    }

    public void addRowToTable() {
        DefaultTableModel model = (DefaultTableModel) jtCarros.getModel();
        model.getDataVector().removeAllElements();//remove todas as linhas
        model.fireTableDataChanged();
        Object rowData[] = new Object[9];
        CarroServicos carroS = ServicosFactory.getCarroServicos();
        PessoaServicos pessoaS = ServicosFactory.getPessoaServicos();
        for (Carro carro : carroS.getCarros()) {
            rowData[0] = carro.getPlaca();
            rowData[1] = carro.getMarca();
            rowData[2] = carro.getModelo();
            rowData[3] = carro.getCor();
            rowData[4] = carro.getAnoFab();
            rowData[5] = carro.getAnoMod();
            rowData[6] = carro.getTpCambio();
            rowData[7] = carro.getCombustivel();
            rowData[8] = carro.getProprietario().getNome();
            model.addRow(rowData);
        }

    }

    public boolean validaInputs() {
        if (jtfPlaca.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Placa obrigatório!");
            jtfPlaca.requestFocus();
            return false;
        } else if (jtfMarca.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Marca obrigatório!");
            jtfMarca.requestFocus();
            return false;
        } else if (jtfModelo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Modelo obrigatório!");
            jtfModelo.requestFocus();
            return false;
        } else if (jtfCor.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Cor obrigatório!");
            jtfCor.requestFocus();
            return false;
        } else if (jtfAnoFab.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Ano de Fabricação obrigatório!");
            jtfAnoFab.requestFocus();
            return false;
        } else if (jtfAnoMod.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Ano do Modelo obrigatório!");
            jtfAnoMod.requestFocus();
            return false;
        } else if (!jrbManual.isSelected() && !jrbAuto.isSelected()) {
            JOptionPane.showMessageDialog(this, "Campo Cambio obrigatório!");
            //jtftpCambio.requestFocus();
            return false;
        } else if (jcbCombustivel.getSelectedItem().equals("Selecione...")) {
            JOptionPane.showMessageDialog(this, "Campo Combustivel obrigatório!");
            jcbCombustivel.requestFocus();
            return false;
        } else if (jtfProprietario.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Proprietario obrigatório!");
            jtfProprietario.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bgCambio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfCor = new javax.swing.JTextField();
        jtfProprietario = new javax.swing.JTextField();
        jtfAnoMod = new javax.swing.JFormattedTextField();
        jtfAnoFab = new javax.swing.JFormattedTextField();
        jtfMarca = new javax.swing.JTextField();
        jtfModelo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jbFechar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCarros = new javax.swing.JTable();
        jtfPlaca = new javax.swing.JFormattedTextField();
        jlProp = new javax.swing.JLabel();
        jcbCombustivel = new javax.swing.JComboBox<>();
        jrbManual = new javax.swing.JRadioButton();
        jrbAuto = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("* Placa:");

        jLabel2.setText("* Marca:");

        jLabel3.setText("* Modelo:");

        jLabel4.setText("* Ano Fabricaçao:");

        jLabel5.setText("* Ano Modelo:");

        jLabel6.setText("* Cor:");

        jLabel7.setText("* Câmbio:");

        jLabel8.setText("* Combustível:");

        jLabel9.setText("* Proprietário:");

        jtfProprietario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfProprietarioFocusLost(evt);
            }
        });
        jtfProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProprietarioActionPerformed(evt);
            }
        });
        jtfProprietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfProprietarioKeyTyped(evt);
            }
        });

        try {
            jtfAnoMod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfAnoMod.setToolTipText("informe o ano com 4 digitos");
        jtfAnoMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfAnoModFocusLost(evt);
            }
        });
        jtfAnoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAnoModKeyTyped(evt);
            }
        });

        try {
            jtfAnoFab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfAnoFab.setToolTipText("informe o ano com 4 digitos");
        jtfAnoFab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAnoFabKeyTyped(evt);
            }
        });

        jtfMarca.setToolTipText("i");

        jtfModelo.setToolTipText("");

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jtCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "Cor", "Ano Fabricação", "Ano Modelo", "Câmbio", "Combustível", "Proprietário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCarrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtCarros);

        try {
            jtfPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-#H##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPlacaActionPerformed(evt);
            }
        });

        jlProp.setToolTipText("");
        jlProp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jcbCombustivel.setMaximumRowCount(6);
        jcbCombustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Alcool", "Gasolina", "GNV", "Flex", "Diesel" }));

        bgCambio.add(jrbManual);
        jrbManual.setText("Manual");
        jrbManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbManualActionPerformed(evt);
            }
        });

        bgCambio.add(jrbAuto);
        jrbAuto.setText("Auto");
        jrbAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbDeletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbFechar)
                                .addGap(133, 133, 133)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfProprietario)
                            .addComponent(jtfPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfAnoMod, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfAnoFab, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbCombustivel, javax.swing.GroupLayout.Alignment.LEADING, 0, 115, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jlProp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbManual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbAuto))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jtfAnoFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jtfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAnoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jcbCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbManual)
                    .addComponent(jrbAuto))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbLimpar)
                            .addComponent(jbSalvar)
                            .addComponent(jbEditar)
                            .addComponent(jbDeletar)
                            .addComponent(jbFechar))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProprietarioActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        if (jbLimpar.getText().equals("Limpar")) {
            limparCampos();
        } else {
            jbEditar.setEnabled(false);
            jbLimpar.setText("Limpar");
            jbSalvar.setText("Salvar");
            limparCampos();
        }


    }//GEN-LAST:event_jbLimparActionPerformed

    private static String bgCambio2;

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        if (validaInputs()) {
            PessoaServicos pessoaS = ServicosFactory.getPessoaServicos();
            CarroServicos carroS = ServicosFactory.getCarroServicos();
            String placa = jtfPlaca.getText().toUpperCase();
            String marca = jtfMarca.getText().toUpperCase();
            String modelo = jtfModelo.getText().toUpperCase();
            int anoFab = Integer.parseInt(jtfAnoFab.getText());
            int anoMod = Integer.parseInt(jtfAnoMod.getText());
            String cor = jtfCor.getText().toUpperCase();
            String cambio = bgCambio2.toUpperCase();
            String combustivel = jcbCombustivel.getSelectedItem().toString();
            Pessoa proprieario = pessoaS.getPessoaByDoc(jtfProprietario.getText());

            Carro c = new Carro(placa, marca, modelo, anoFab, anoMod, cor, cambio, combustivel, proprieario);
            if (jbSalvar.getText().equals("Salvar")) {
                carroS.cadastrarCarro(c);
            } else {
                carroS.atualizarCarro(c);
            }
            addRowToTable();
            jbLimpar.doClick();

        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        jbDeletar.setVisible(false);
        jbSalvar.setText("Confirmar");
        jbLimpar.setText("Cancelar");
        jtfPlaca.setEnabled(false);
        
        int linha = jtCarros.getSelectedRow();
        String placa = (String)jtCarros.getValueAt(linha, 0);
        CarroServicos carroS = ServicosFactory.getCarroServicos();
        Carro c = carroS.getCarroByDoc(placa);
        jtfProprietario.setText(c.getProprietario().getCpf());
        jtfPlaca.setText(c.getPlaca());
        jtfAnoFab.setText(Integer.toString(c.getAnoFab()));
        jtfAnoMod.setText(Integer.toString(c.getAnoMod()));
        jtfCor.setText(c.getCor());
        jtfMarca.setText(c.getMarca());
        jtfModelo.setText(c.getModelo());
        jcbCombustivel.setSelectedItem(c.getCombustivel());
        jlProp.setText(c.getProprietario().getNome());
        bgCambio2 = c.getTpCambio();
        
        if (c.getTpCambio().equalsIgnoreCase("Manual")) {
            jrbManual.setSelected(true);
        }else{
            jrbAuto.setSelected(true);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        // TODO add your handling code here:
        int linha = jtCarros.getSelectedRow();
        String placa = (String) jtCarros.getValueAt(linha, 0);
        CarroServicos carroS = ServicosFactory.getCarroServicos();
        Object[] btnMSG = {"Sim", "Não"};
        int resp = JOptionPane.showOptionDialog(this, "Deseja realmente deletar " + placa, ".: Deletar :.", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, btnMSG, btnMSG[1]);
        if (resp == 0 ) {
            carroS.deletarCarro(placa);
            addRowToTable();
            JOptionPane.showMessageDialog(this, "Carro deletado com sucesso!");
        }else{
            JOptionPane.showMessageDialog(this, "Ok, delete cancelado pelo usuário!");
        }
        jbLimpar.doClick();
    }

    public void limparCampos() {
        jtfPlaca.setText("");
        jtfMarca.setText("");
        jtfModelo.setText("");
        jtfAnoFab.setText("");
        jtfAnoMod.setText("");
        jtfCor.setText("");
        jcbCombustivel.setSelectedIndex(0);
        bgCambio.clearSelection();
        jtfProprietario.setText("");
        jlProp.setText("");

    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jtCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCarrosMouseClicked
        // TODO add your handling code here:
        jbDeletar.setVisible(true);
        jbEditar.setEnabled(true);
    }//GEN-LAST:event_jtCarrosMouseClicked

    private void jtfProprietarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfProprietarioFocusLost
        // TODO add your handling code here:
        if (!jtfProprietario.getText().equals("")) {

            PessoaServicos pessoaS = ServicosFactory.getPessoaServicos();
            String cpf, nome;
            cpf = jtfProprietario.getText();
            if (Validadores.isCPF(cpf)) {
                nome = pessoaS.getPessoaByDoc(cpf).getNome();

                if (nome == null) {
                    JOptionPane.showMessageDialog(this, "Pessoa nao existe!");
                    jtfProprietario.requestFocus();
                } else {
                    Object[] btnMSG = {"Sim", "Não"};
                    int resp = JOptionPane.showOptionDialog(this, "Este é o proprietário?\n" + nome, ".: Proprietário :.",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                            null, btnMSG, btnMSG[1]);
                    if (resp == 0) {
                        jlProp.setText(nome);
                    } else {
                        jtfProprietario.requestFocus();
                        jtfProprietario.setText(nome);

                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "CPF inválido!");
                jtfProprietario.requestFocus();
            }
        }

    }//GEN-LAST:event_jtfProprietarioFocusLost

    private void jtfProprietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProprietarioKeyTyped
        // TODO add your handling code here:
        String num = "0123456789";
        if (!num.contains(evt.getKeyChar() + "")) {
            evt.consume();

        }
    }//GEN-LAST:event_jtfProprietarioKeyTyped

    private void jtfAnoModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfAnoModFocusLost
        // TODO add your handling code here:
        int anoFab = Integer.parseInt(jtfAnoFab.getText());
        int anoMod = Integer.parseInt(jtfAnoMod.getText());

        if (!Validadores.validarAnoCarro(anoFab, anoMod)) {
            JOptionPane.showMessageDialog(this, "informações de ano inválidas!");
            jtfAnoFab.requestFocus();
        }

    }//GEN-LAST:event_jtfAnoModFocusLost

    private void jtfAnoModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAnoModKeyTyped
        // TODO add your handling code here:
        if (jtfAnoMod.getText().length() <= 4) {
            String num = "0123456789";
            if (!num.contains(evt.getKeyChar() + "")) {
                evt.consume();

            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jtfAnoModKeyTyped

    private void jtfAnoFabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAnoFabKeyTyped
        // TODO add your handling code here:
        if (jtfAnoFab.getText().length() <= 4) {
            String num = "0123456789";
            if (!num.contains(evt.getKeyChar() + "")) {
                evt.consume();

            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jtfAnoFabKeyTyped

    private void jrbManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbManualActionPerformed
        // TODO add your handling code here:
        bgCambio2 = evt.getActionCommand();
    }//GEN-LAST:event_jrbManualActionPerformed

    private void jrbAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAutoActionPerformed
        // TODO add your handling code here:
        bgCambio2 = evt.getActionCommand();
    }//GEN-LAST:event_jrbAutoActionPerformed

    private void jtfPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbCombustivel;
    private javax.swing.JLabel jlProp;
    private javax.swing.JRadioButton jrbAuto;
    private javax.swing.JRadioButton jrbManual;
    private javax.swing.JTable jtCarros;
    private javax.swing.JFormattedTextField jtfAnoFab;
    private javax.swing.JFormattedTextField jtfAnoMod;
    private javax.swing.JTextField jtfCor;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JFormattedTextField jtfPlaca;
    private javax.swing.JTextField jtfProprietario;
    // End of variables declaration//GEN-END:variables
}
